[package]
name = "jaeger_remote_tracer"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
clap = "2"
fibers = "0.1"
futures = "0.1"
htrpc = "0.0.15"
rustracing = "0.1"
rustracing_jaeger = "0.1"
serde = "1"
serde_derive = "1"
trackable = "0.2"