[package]
name = "jaeger_remote_tracer"
version = "0.1.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
clap = "4"
fibers = "0.1"
futures = "0.1"
htrpc = "0.0.18"
rustracing = "0.6"
rustracing_jaeger = "0.9"
serde = {version = "1", features = ["derive"] }
trackable = "1"